ausocean/openfish

- api/api.go
- api/api/result_types.go
- api/handlers/annotations.go
- api/handlers/capturesource.go
- api/handlers/videostream.go
Resolves Issue #15 
This uses a custom error handler to construct HTTP responses with a JSON body of {"message": "<>"} and with a custom HTTP status code (or 500 if it is not supplied).
Advantages of this method is it simplifies result_types.go, and unhandled errors will also be formatted nicely. The reason behind JSON formatted responses and control over HTTP status codes is that it will make it easier for client code to consume and understand errors from our API
**old:**
```
HTTP/1.1 400 Bad Request
Date: Wed, 21 Jun 2023 03:47:31 GMT
Content-Type: application/json
Content-Length: 37
Connection: close
{
"message": "invalid json in request"
}
```
**new:**
```
HTTP/1.1 400 Bad Request
Date: Wed, 21 Jun 2023 03:46:02 GMT
Content-Type: application/json
Content-Length: 103
Connection: close …
```
> Use error handler func to simplify error handling

- api/api.go
- api/handlers/capturesource.go
- datastore/datastore.go
Closes #19 
Depends on videostreams being implemented first because we need to check there are none for a capture source before deleting
> Support updating and deleting capture sources

- api/api.go
- api/capturesource_test.go
- api/handlers/annotations.go
- api/handlers/videostream.go
- api/model/videostream.go
- api/videostream_test.go
Resolves issue #5 
Adds support for creating video streams (such as uploading past streams), and starting and finishing live streams.
Adds support for updating and deleting existing streams.
Adds support for fetching video stream, filtering by capture source or by timespan
API test changes have been split off into a separate PR #14 
Error handling improvements have been split off into a separate PR #15
> Create datastore for video stream data

- api/api.go
- api/handlers/videostream.go
- api/model/annotations.go
The openfish API did not include the correct headers for the web browser, causing a CORS issue. This is because localhost:3000 and localhost:3333 / localhost:80 used by the web app are different origins, and so the browser sees this as a security issue if you do not say otherwise with AllowOrigins headers.
> Fix CORS issue

- datastore/datastore.go
The subtime bit mask is now derived from SubTimeBits.
Also, fixed SplitIDKey to not return a negative ID.
> SubTimeBits now exported

- openfish-webapp/.dockerignore
- openfish-webapp/Dockerfile
- openfish-webapp/README.md
Adds docker support for the web app
The docker file uses a node 20.5 image for building the web app using vite, and then a second image using nginx as the http server
> Add docker support

- openfish-webapp/index.html
- openfish-webapp/src/index.css
- openfish-webapp/src/watch-stream.ts
- openfish-webapp/vite.config.ts
- openfish-webapp/watch.html
Closes issue #66 
The OpenFish web application for viewing videostreams will need to support additional pages, but the vite project is currently set up for just a single page (index.html). 
This PR changes it so we can add new pages. The url for viewing streams is now:
`localhost:5173/watch.html?id=<Video-stream ID>`
> Make the webapp a multi-page application

- api/ds_client/ds_client.go
- api/model/annotations.go
- api/model/capturesource.go
- api/model/videostream.go
Registers our video stream, annotation and capture source entities so we can use openfish in local mode
> Register entities so we can use the filestore

- openfish-webapp/src/annotation-card.ts
- openfish-webapp/src/api.types.ts
- openfish-webapp/src/datetime.ts
- openfish-webapp/src/stream-list.ts
- openfish-webapp/streams.html
- openfish-webapp/vite.config.ts
Closes issue #63 
Adds a list of videostreams user's can browse
Currently, the API is reporting that the total number of videostreams is the same as the limit, this is incorrect which is causing a bug in the user interface - that the next and previous buttons are greyed out. This is a separate issue and will have a separate MR.
Some code from the annotation card file has been refactored out into the datetime.ts file, and is reused here for displaying stream dates in the table
[Screencast from 2023-12-01 16-10-17.webm](https://github.com/ausocean/openfish/assets/33645953/eae4bfca-bfaa-4cb9-8134-0a1512f2408e)
> Add list of streams on /streams.html page

- datastore/datastore.go
Openfish uses limit and offset to fetch a small selection of the available data - this is done so that request time stays reasonable as the number of entities in google datastore gets very large.
This PR adds support for limit and offset to the filestore, so that we can use openfish locally for testing.
> Add support for limit and offset to the Filestore

- api/api.go
- api/handlers/annotations.go
- api/handlers/capturesource.go
- api/handlers/videostream.go
- api/model/annotations.go
- api/services/annotations.go
- api/services/capturesources.go
- api/services/videostream.go
Handlers are now only responsible for the handling of the HTTP request and response. Reading and writing to the datastore, and other logic for ensuring we don't have videostreams pointing to non-existent capture sources etc, has been moved into services. This will make code easier to understand, and make unit testing easier.
> Refactor API code into services package

- openfish-webapp/package.json
- openfish-webapp/pnpm-lock.yaml
- openfish-webapp/src/annotation-card.ts
- openfish-webapp/src/api.types.ts
- openfish-webapp/src/capture-source-dropdown.ts
- openfish-webapp/src/index.css
- openfish-webapp/src/stream-filter.ts
- openfish-webapp/src/stream-list.ts
- openfish-webapp/streams.html
Improves on the layout of the streams.html page. Adds a menu sidebar for filtering streams. Refactors some code to use `@state` instead of `@property` where appropriate. 
The layout uses css grid with named dividers - this is what the grid regions look like with dev tools enabled
This PR adds another dependency: `@fooloomanzoo/datetime-picker` - it is used for the date picker. It is a webcomponent/custom element.
> Improve layout of streams.html page

- openfish-webapp/src/annotation-overlay.ts
- openfish-webapp/src/watch-stream.ts
- openfish-webapp/src/youtube-player.ts
- openfish-webapp/watch.html
Part of issue #65 
This refactors out annotation-overlay as a component in preparation for adding support to create annotations. 
This is required because as a separate component, annotation-overlay can be hidden from the page when a user is creating a new annotation and a different (yet to be created component) can be shown to let the user draw the bounding box
Cannot be merged until PR #85  is merged
> Refactor out annotation-overlay as component

- .gcloudignore
- api/ds_client/ds_client.go
- api/main.go
- app.yaml
- docker/api
- docs/api/video-streams.md
- docs/getting-started.md
- openfish-webapp/.env
- openfish-webapp/src/capture-source-dropdown.ts
- openfish-webapp/src/stream-list.ts
- openfish-webapp/src/watch-stream.ts
Openfish can now be deployed to appengine.
See here:
https://openfish.appspot.com/streams.html
Changes:
- app.yaml and .gcloudignore added for deploying to google appengine
- Few changes in /api to make it work when deployed
- Remove hardcoded localhost:3000 from Openfish webapp
> Deploy to appengine

- docs/getting-started.md
This adds documentation on how to get google datastore working with openfish
> Add google cloud setup info to docs

- openfish-webapp/src/datetime.ts
- openfish-webapp/src/playback-controls.ts
Currently, we display the number of seconds, which for a many hour stream is a very large number. This changes it to display the number of hours, minutes and seconds
> Fix display of time on playback controls

- openfish-webapp/src/youtube-player.ts
There is a bug where clicking pause will jump the video back to the start of playback. This fixes that issue
> Fix youtube player jump to start bug

- docs/api/video-streams.md
The video streams are already residing on YouTube or vidgrind, they are not really being created, instead we are registering their existence with openfish. This change makes the docs clearer.
> Use the term 'register' instead of 'create' in the videostream API docs

- api/entities/species.go
- api/handlers/species.go
- api/main.go
- api/services/capturesource_test.go
- api/services/species.go
- api/services/species_test.go
- docs/.vitepress/config.mts
- docs/api/species.md
- openfish-webapp/src/api.types.ts
Adds a new API which we can use for suggesting species to a user when they are annotating video.
Currently, the API is not smart, it does not recommend species in any order, however my intention would be to make it return species from the current videostream first (sorted by frequency), then species from the current capture source (sorted by frequency), and then after that, the rest of the species (sorted by frequency).
> Species guide api

- api/api/result_types.go
- api/handlers/annotations.go
- api/handlers/auth.go
- api/main.go
- app.yaml
This adds support for user authentication using gcloud IAP. By default it is disabled, you need to pass the command line flag --iap or set the environmental argument IAP="true" to enable it. 
Command line flags and environmental arguments can now both be used to configure options.
IAP is active on https://openfish.appspot.com/streams.html
> Add user authentication using gcloud IAP

- openfish-webapp/src/webcomponents/confirm-dialog.ts
Adds a dialog asking for user confirmation before performing an action.
```html
<confirm-dialog>Your message here</confirm-dialog>
```
```typescript
const confirmDialog = document.querySelector("confirm-dialog") as ConfirmDialog
// show() displays the dialog, and takes a callback as an argument, that will
// fire if the user confirms.
confirmDialog.show(()=>console.log('user confirmed'))
```
> Add confirm dialog component

- openfish-webapp/vite.config.ts
- package.json
- pnpm-lock.yaml
A newly added html file was not being included in the build step by vite. The inputs are now no longer hardcoded - using a glob, so this should not happen again.
> Use glob to determine vite build inputs

- openfish-webapp/src/webcomponents/annotation-displayer.ts
Adds a much more helpful title to the annotation bounding box.
> Display common and latin name on annotations

- api/entities/users.go
- api/handlers/auth.go
- api/handlers/capturesource.go
- api/handlers/user.go
- api/main.go
- api/middleware/authentication.go
- api/services/capturesource_test.go
- api/services/users.go
- api/services/users_test.go
Closes #115 
Adds the concept of users to openfish. Users are identified by their email address. Users have one of 4 roles.
**Admin role**
An admin would be able to add and remove annotations, videostreams, capturesources, users, and species.
**Curator role**
A curator can select streams for classification. An application would be for teachers who could choose streams for their students to classify
**Annotator role**
By default users would have the annotator role, which lets them add annotations, and delete their own annotations.
**Readonly role**
A readonly user would only be able to look at annotations, not make any. This could be for unauthenticated users who only want to watch.
A new middleware - Guard is used to restrict access to APIs by user role. **When ran locally (non-iap mode), …
> Add role based access control

- docs/.vitepress/config.mts
- docs/api/authentication.md
- docs/api/index.md
- docs/api/roles-and-permissions.md
- docs/api/users.md
We recently added user authentication (PR #108) and user roles / permissions (PR #122), which adds new APIs (for managing users), adds new ways existing APIs can fail (unauthorised & forbidden HTTP codes) and a new command line flag, so these need to be documented.
> Add documentation on roles, users and authentication

- api/services/inaturalist_taxa.go
- api/services/inaturalist_taxa_test.go
Related to issue #127 - expand the list of species
Adds two new functions for querying the iNaturalist Taxa API.
GetTaxonByName gets a taxon from the API by providing a name e.g. infraorder cetacea. This is handly because we need the IDs to do descendant lookups.
GetSpeciesByDescendant filters all taxa to be species only, and which are descendant of a particular taxon. The iNaturalist API is paginated - it does not return all the results, just a portion, so we need to make multiple requests until there is no more pages of data to fetch.
> Add service for querying the iNaturalist Taxa API

- api/entities/species.go
- api/handlers/species.go
- api/main.go
- api/services/species.go
- api/services/species_test.go
Related to issue #127 
Adds an API to import species from iNaturalist, updating existing species with changes, or creating new records in the datastore if they do not already exist.
> Add species import API from iNaturalist

- cmd/openfish/entities/annotations.go
- cmd/openfish/handlers/videostream.go
- cmd/openfish/services/annotations_test.go
- cmd/openfish/services/videostream_test.go
- cmd/openfish/types/videotime/videotime.go
- cmd/openfish/types/videotime/videotime_test.go
Closes issue #113.
In many of our APIs we use timestamps to specify moments in a video. This is calculated as start timestamp + time elapsed. This was a mistake, as we are needlessly converting times backwards and forwards. It would be much easier to store the video time (e.g. 01:03:22.500) rather than ISO 8601 timestamp (2024-03-03T09:03:22.500Z).
This PR adds a new type - videotime which unlike time.Time does not have a date component or timezones. 
Note, changes to the frontend will be needed too, that is another PR
> Use playback time instead of timestamps for annotations (API only)

- cmd/openfish/entities/annotations.go
- cmd/openfish/handlers/annotations.go
- cmd/openfish/handlers/videostream.go
- cmd/openfish/services/annotations.go
- cmd/openfish/services/annotations_test.go
- cmd/openfish/services/videostream.go
- cmd/openfish/services/videostream_test.go
- cmd/openfish/types/timespan/timespan.go
- cmd/openfish/types/videotime/videotime.go
After changing away from time.Time for video times, timespans are now not being stored in the datastore. This adds a Load and Save method to timespan to fix this bug.
> Time-spans are stored in datastore correctly

- .gcloudignore
- app.yaml
Deployment was broken because of renaming of a directory to `cmd/openfish`
> Fix deployment to Google AppEngine

- openfish-webapp/src/utils/api.types.ts
- openfish-webapp/src/utils/datetime.ts
- openfish-webapp/src/webcomponents/annotation-card.ts
- openfish-webapp/src/webcomponents/playback-controls.ts
- openfish-webapp/src/webcomponents/watch-stream.ts
This updates the client to handle video times using the hh:mm:ss format, matching the API
> Use times in format hh:mm:ss on client

- cmd/openfish/handlers/species.go
- cmd/openfish/services/inaturalist_taxa.go
A lot of the species in iNaturalist do not have photos. Users of openfish may have difficulty making correct identifications without a reference picture so it is probably best if we just skip these and don't import them. I have gone and deleted the existing ones missing pictures from the datastore.
> Skip importing species if they do not have a photo

- cmd/openfish/entities/annotations.go
- cmd/openfish/entities/capturesource.go
- cmd/openfish/entities/species.go
- cmd/openfish/entities/users.go
- cmd/openfish/entities/videostream.go
- datastore/datastore.go
Closes issue https://github.com/ausocean/openfish/issues/3
Adds a default implementation for encoding/decoding entities using JSON marshal / unmarshal. 
If you want to have custom implementations for encode and decode, you can implement the EntityEncoder interface (Encode method) and the EntityDecoder interface (Decode method)
Changes are backwards compatible and should not require any changes to consuming code.
> Add a default implementation for encode/decode

- .github/workflows/code-checks.yaml
- .github/workflows/deploy-documentation.yaml
- .github/workflows/deploy-openfish.yaml
- openfish-webapp/package.json
Using github actions reporters means the CI errors will show up in github's UI.
Actions have been updated because they use an older version of node and it is displaying a warning
> Use github reporter in CI & update actions

- cmd/openfish/ds_client/ds_client.go
- cmd/openfish/services/annotations.go
- cmd/openfish/services/annotations_test.go
- cmd/openfish/services/species.go
- cmd/openfish/services/species_test.go
Adds validation to observations to check that the species exists in our datastore.
> Limit annotations to known species in our datastore

- cmd/openfish/entities/annotations.go
- cmd/openfish/handlers/annotations.go
- cmd/openfish/services/annotations.go
- cmd/openfish/types/timespan/timespan.go
- cmd/openfish/types/videotime/videotime.go
If we want to be able to sort by the start time of an annotation, we need them to be indexable in our datastore. This flattens timespan, and removes google datastore specific code
> Flatten annotation entity so timespans can be indexed

- cmd/openfish/entities/species.go
- cmd/openfish/services/species.go
Search queries are case insensitive: e.g. `wHal` matches `Whale Shark`
Search queries will now match not just the first word in a species' common name: e.g. `shar` matches `Whale Shark`
Search queries will now match on scientific names: e.g. `rhin` matches `Rhincodon typus`
> Search-improvement

- docker/api
api was renamed to cmd/openfish, reflect this in docker build
> docker: update api build path to reflect name changes

- openfish-webapp/capturesources.html
- openfish-webapp/src/webcomponents/data-table.ts
- package.json
- pnpm-lock.yaml
This adds a new component for making tables easier. The motivation behind this is that there will be lots of code duplication otherwise, once I start adding tables for other data in openfish, such as users or species.
**Usage:**
```html
<data-table src="/api/v1/capturesources" colwidths="2fr 3fr 2fr 2fr">
<dt-col title="Name" key="name"></dt-col>
<dt-col title="Camera Hardware" key="camera_hardware"></dt-col>
<dt-col title="Site ID" key="site_id"></dt-col>
<dt-col title="Location" key="location"></dt-col>
</data-table>
```
> Refactor capture sources page to use a generic data table component

- openfish-webapp/.env
- openfish-webapp/capturesources.html
- openfish-webapp/src/webcomponents/capture-source-dropdown.ts
- openfish-webapp/src/webcomponents/capturesource-list.ts
- openfish-webapp/src/webcomponents/data-table.ts
- openfish-webapp/src/webcomponents/form-dialog.ts
- openfish-webapp/src/webcomponents/observation-editor.ts
- openfish-webapp/src/webcomponents/stream-list.ts
- openfish-webapp/src/webcomponents/user-provider.ts
- openfish-webapp/src/webcomponents/watch-stream.ts
- openfish-webapp/vite.config.ts
Remove environmental variable VITE_API_HOST and use Vite's proxy during development
This makes things simpler and makes the development environment closer to what is on the live site, by putting the /api endpoints on the same origin.
> Remove environmental variable VITE_API_HOST and use Vite's proxy 

- .github/workflows/deploy-openfish.yaml
Currently, openfish is being deployed automatically on every push to master, which is too much. Instead, it now is deployed only when we tag a release
> Deploy openfish only on tagged releases

- cmd/openfish/handlers/annotations.go
- cmd/openfish/services/annotations.go
- index.yaml
Filtering by video stream ID was not implemented so when viewing video streams on openfish, annotations from other videos would appear.
> Add functionality to filter annotations by video stream ID

- cmd/openfish/handlers/capturesource.go
- openfish-webapp/admin/capturesources.html
This adds a new button for editing a capture source which brings up a dialog where you can change its location, name, site ID and camera hardware description
Also fixes a nil dereference error when updating a capture source
> Support editing capture sources

- openfish-webapp/admin/videostreams.html
- openfish-webapp/src/utils/datetime.ts
- openfish-webapp/src/webcomponents/data-select.ts
- openfish-webapp/src/webcomponents/input-datetime.ts
This adds a new button for editing a video stream which brings up a dialog where you can change its start and end time, reasssign its capture source and update its stream URL. Like creating videostreams, this handles the local user's timezone, performing conversions as needed. For reviewers it will show Australia/Adelaide instead.
> Support editing video streams

- .github/dependabot.yml
This was done because these updates happen too often for us to keep up.
> Update dependabot.yml to monthly

- cmd/openfish/services/annotations.go
- cmd/openfish/services/annotations_test.go
- pnpm-lock.yaml
- ui/package.json
This was done to make a test pass. Namely TestAnnotationAddNonExistingSpeciesIdentification. This can be skipped with the -short flag but I didn't realise that. It's fixed now so it's no longer behind the flag.
> services/annotations: check species before adding to annotation

- cmd/openfish/services/users.go
This was done because the TestGetUserByEmail function was panicing due to assuming this function returns a valid user or an error.
See issue #331
> cmd/openfish/services: return ErrNoSuchEntity if no user found by email
