ausocean/openfish

datastore/datastore.go, datastore/datastore_test.go
Merging in some methods originally developed for another project.
=> Added Create and Apply methods

api/handlers/annotations.go, api/handlers/videostream.go, api/model/annotations.go, go.mod, go.sum
closes #7 
depends on https://github.com/ausocean/openfish/pull/10
=> Create datastore for annotations

datastore/cache.go, datastore/cache_test.go, datastore/datastore.go, datastore/datastore_test.go
This is the first step at implementing a caching layer.
The next step is to integrate it with datastore.go.
=> Datastore cache

README.md
=> added README from wiki homepage (originally from google docs)

docs/api/API-Documentation.md, docs/api/Annotations.md, docs/api/Capture-Sources.md, docs/api/General-Usage-Notes.md, docs/api/Video-Streams.md
=> add docs directory containing existing api documentation

openfish-webapp/src/api.types.ts
=> 29 add types

openfish-webapp/index.html, openfish-webapp/src/annotation-card.ts
This adds a custom element for displaying an annotation.
=> Create web app for viewing video streams: display annotations

openfish-webapp/index.html, openfish-webapp/package.json, openfish-webapp/pnpm-lock.yaml, openfish-webapp/src/datetime.ts, openfish-webapp/src/playback-controls.ts, openfish-webapp/src/reset.css.ts, openfish-webapp/src/video-player.ts, openfish-webapp/src/youtube-player.ts
This adds a video player for viewing Youtube videos. In the future, this could support vidgrind videos or other videos
=> Create web app for viewing video streams: Add video player for videostream playback

openfish-webapp/index.html, openfish-webapp/src/app.ts
This adds a simple one page web app for viewing video streams.
Initially only youtube is supported using the youtube Iframe player API. Vidgrind will come later.
Annotations are displayed using card components (providing all the text data), a rectangular overlay on the video using svg (providing bounding box info), and as a coloured band on the playback controls (providing time of occurrence at a glance)
- Sometimes the video freezes playback. Something to investigate.
- Firefox 117.0
- Chromium 117.0.5938.92
=> Create web app for viewing video streams: Add openfish-app component

api/handlers/annotations.go, api/handlers/capturesource.go, api/handlers/videostream.go, api/model/annotations.go, api/model/capturesource.go, api/model/videostream.go
=> Use constants for the datastore entity names

openfish-webapp/README.md, openfish-webapp/biome.json, openfish-webapp/package.json, openfish-webapp/pnpm-lock.yaml, openfish-webapp/src/api.types.ts
Rome was discontinued and forked, now called Biome.
=> Replace rome formatter/linter with biome

openfish-webapp/biome.json, openfish-webapp/src/annotation-card.ts, openfish-webapp/src/datetime.ts, openfish-webapp/src/playback-controls.ts, openfish-webapp/src/video-player.ts, openfish-webapp/src/watch-stream.ts, openfish-webapp/src/youtube-player.ts
This fixes all the issues that biome has found in the typescript code. Not ready to be merged, waiting on PR #55.
=> Fix linting issues in project

openfish-webapp/biome.json, openfish-webapp/src/playback-controls.ts
Change to allow non-null assertions in our code
=> Alow non-null assertions in our code

api/ds_client/ds_client.go, api/model/annotations.go, api/model/capturesource.go, api/model/videostream.go
Closes issue #53 which was preventing compiling
=> Implement Copy and Cache for Entity structs

.github/workflows/code-checks.yaml, api/capturesource_test.go, api/videostream_test.go
Closes issue #59 
This adds a Github Action workflow that checks for code issues. This checks for issues with go code and typescript code in the api and openfish-webapp directories.
Both workflows are failing, PRs 54 & 55 will bring fixes.
=> Setup github actions

.github/workflows/deploy-documentation.yaml, docs/.vitepress/config.mts
Deploys our documentation to github pages when a commit is made on master branch.
View here
https://ausocean.github.io/openfish/
=> Deploy documentation to github pages

.github/workflows/code-checks.yaml, openfish-webapp/package.json, openfish-webapp/pnpm-lock.yaml, openfish-webapp/test/datetime.test.ts
Closes issue #73 
Unit tests will run when a new PR is made, so should help us catch regressions.
Adds a single unit test to show it is working. When we add new features we should add tests too.
Have a look at code checks / webapp to see the test results
=> Setup vitest for unit testing of typescript

.github/workflows/code-checks.yaml, api/services/annotations_test.go, api/services/capturesource_test.go, api/services/videostream.go, api/services/videostream_test.go
Adding some unit tests for the services package. This PR is dependent on PR #81 - not ready to merge. GIthub actions is modified to run all tests too
=> Write unit tests for services package

api/ds_client/ds_client.go, api/entities/annotations.go, api/entities/capturesource.go, api/entities/videostream.go, api/handlers/annotations.go, api/handlers/capturesource.go, api/handlers/videostream.go, api/services/annotations.go, api/services/annotations_test.go, api/services/capturesources.go, api/services/videostream.go, api/services/videostream_test.go
Entity is a better name and is consistent with what we call them in datastore
=> Rename model to entities

openfish-webapp/src/annotation-card.ts, openfish-webapp/src/index.css, openfish-webapp/src/playback-controls.ts, openfish-webapp/src/stream-list.ts, openfish-webapp/src/video-player.ts, openfish-webapp/src/watch-stream.ts, openfish-webapp/watch.html
Issue #65 
This adds a button to the watch page and does some refactoring of how colours are defined in the index.css file.
=> Preliminary work for creating annotations

docs/getting-started.md, openfish-webapp/README.md
This updates the documentation with a getting started page. It has instructions on how to get started using docker and how to get started for development.
=> Update getting started documentation

.github/workflows/deploy-openfish.yaml
This automatically deploys our code to appengine on a push to master.
=> Automatically deploy to Appengine using Github Actions

openfish-webapp/src/observation-editor.ts, openfish-webapp/src/playback-controls.ts, openfish-webapp/src/reset.css.ts, openfish-webapp/src/watch-stream.ts
Adds buttons to set the start and end time of an annotation
Dependent on PR: https://github.com/ausocean/openfish/pull/100
=> Add buttons to set start and end times

docs/.vitepress/config.mts, docs/contributing.md, docs/getting-started.md
=> Add a contribution page to our documentation

openfish-webapp/src/api.types.ts, openfish-webapp/src/bounding-box-creator.ts, openfish-webapp/src/watch-stream.ts
[Screencast from 2024-03-06 16-19-37.webm](https://github.com/ausocean/openfish/assets/33645953/ad9d6787-4801-4169-a6f4-1bd5b84417dd)
Need to get rid of the more videos suggestions bar
=> Add bounding box creator

openfish-webapp/src/utils/geo.ts, openfish-webapp/src/webcomponents/location-picker.ts, package.json, pnpm-lock.yaml
The location picker form element is useful for getting a lat-long from the user. I plan on using it for picking the location of a capture source. You can paste lat long coordinates or click on the map to set the location. To get the selected location you can use the same code you would for an ordinary form input.
```typescript
// Use this as your form submit handler
submit(e: SubmitEvent) {
e.preventDefault()
const formdata = new FormData(e.target as HTMLFormElement)
console.log(formdata.get('location'))
}
```
[Screencast from 2024-04-17 09-56-41.webm](https://github.com/ausocean/openfish/assets/33645953/0df6d28f-a3db-43ac-b104-d72bcb0ed43f)
=> Add location picker form element

openfish-webapp/index.html, openfish-webapp/src/styles/buttons.css, openfish-webapp/src/styles/index.css, openfish-webapp/src/webcomponents/site-nav.ts
Adds a simple homepage to openfish so that when users visit they do not see the placeholder page
=> Add homepage to openfish

api/entities/videostream.go, api/handlers/annotations.go, api/handlers/videostream.go, api/services/annotations_test.go, api/services/capturesource_test.go, api/services/videostream.go, api/services/videostream_test.go, app.yaml
Users can optionally specify who is allowed to add annotations to the stream.
Closes https://github.com/ausocean/openfish/issues/125
=> Add curation feature

cmd/openfish/handlers/species.go, cmd/openfish/services/inaturalist_taxa.go
Adds more descriptive error messages to help debug issues
=> Use better errors when importing from iNaturalist

openfish-webapp/src/styles/index.css, openfish-webapp/src/webcomponents/annotation-card.ts, openfish-webapp/src/webcomponents/annotation-displayer.ts, openfish-webapp/src/webcomponents/watch-stream.ts
=> Show all annotations for a stream in sidebar

openfish-webapp/watch.html
To use screen space better on the watch page.
=> Reduce size of title

cmd/openfish/api/query_types.go, cmd/openfish/handlers/annotations.go, cmd/openfish/services/annotations.go, openfish-webapp/src/webcomponents/watch-stream.ts
=> Sort-annotations

cmd/openfish/handlers/species.go, cmd/openfish/services/species.go, openfish-webapp/src/webcomponents/observation-editor.ts, openfish-webapp/src/webcomponents/watch-stream.ts
=> Add searching to species selection UI

.github/workflows/code-checks.yaml, docker/api, go.mod, go.sum
This lets us create iterators using functions:
https://go.dev/blog/range-functions
=> Update go to v1.23

cmd/migrations/2024-09-06-fix-search-bug/migration.go, cmd/openfish/services/species.go, cmd/openfish/sliceutils/sliceutils.go, cmd/openfish/sliceutils/sliceutils_test.go
Depends on https://github.com/ausocean/openfish/pull/174
Resolves issue #170
=> Fix searching for species when text matches exactly, or is more than one word

openfish-webapp/capturesources.html, openfish-webapp/index.html, openfish-webapp/src/api/user.ts, openfish-webapp/src/utils/context.ts, openfish-webapp/src/webcomponents/site-nav.ts, openfish-webapp/src/webcomponents/user-provider.ts, openfish-webapp/streams.html, openfish-webapp/watch.html, package.json, pnpm-lock.yaml
This is so we can show user interface items conditionally based upon user role. The user does not have to be passed as props, it is available to its children via the user context.
Here it is used to show the username and role in the navigation menu (top right corner):
=> Add support for accessing logged in user through global context

openfish-webapp/src/styles/index.css, openfish-webapp/src/webcomponents/stream-list.ts
Adds video thumbnails to video streams.
=> Add new UI for viewing streams with video thumbnails

openfish-webapp/admin/users.html, openfish-webapp/src/webcomponents/admin-menu.ts, openfish-webapp/src/webcomponents/data-table.ts
=> Add user management page

openfish-webapp/admin/species.html, openfish-webapp/src/webcomponents/admin-menu.ts, openfish-webapp/src/webcomponents/data-table.ts
Adds species management section to the admin settings page.
=> Add species management page

openfish-webapp/admin/videostreams.html, openfish-webapp/src/webcomponents/admin-menu.ts, openfish-webapp/src/webcomponents/client-timezone.ts, openfish-webapp/src/webcomponents/data-select.ts, openfish-webapp/src/webcomponents/form-dialog.ts, openfish-webapp/src/webcomponents/input-datetime.ts
Closes https://github.com/ausocean/openfish/issues/173
Adds admin page for stream management. Note: timezones are detected automatically, so will be Australia/Adelaide for you
=> Add video stream management page

docs/.vitepress/config.mts, docs/.vitepress/theme/index.mts, docs/developer-docs/api/operations/[operationId].paths.ts, docs/developer-docs/api/tags/[name].paths.ts, package.json, pnpm-lock.yaml
Just updating all the dependencies to the latest versions
=> Update npm dependencies

openfish-webapp/admin/users.html
This adds a new button for editing a user which brings up a dialog where you can change their role.
=> Support editing users

cmd/openfish/api/errorhandler.go, cmd/openfish/capturesource_test.go, cmd/openfish/main.go, cmd/openfish/videostream_test.go
This was done because it would be useful in other projects that use fiber in a similar way.
Not sure where the best place to put it is. Thoughts @scott97 ?
=> api: export errorHandler

cmd/openfish/main.go
This was done to make it more clear what this does.
=> main: document envOrFlag function

openfish-webapp/admin/videostreams.html, openfish-webapp/src/utils/datetime.ts, openfish-webapp/src/webcomponents/data-table.ts
=> Format start and end time of stream nicely

openfish-webapp/src/webcomponents/watch-stream.ts, package.json, pnpm-lock.yaml
Firefox in its later updates is detecting and blocking videos that autoplay. This is breaking playback.
=> Fix broken playback by disabling autoplay

.github/workflows/deploy-documentation.yaml
Updates:
- actions/upload-pages-artifact to v3
- actions/deploy-pages to v4
=> Update github actions versions

cmd/openfish/features/inat.go, cmd/openfish/features/no_inat.go, cmd/openfish/handlers/species.go, cmd/openfish/main.go
=> Put INaturalist import behind a build tag

package.json, pnpm-lock.yaml, site/src/webcomponents/tooltip.ts
tooltip-elem can be triggered on hover or on click.
Usage:
```html
<span id="target">target element</span>
<tooltip-elem
for="target"
trigger="hover"
placement="bottom"
class="bg-slate-900">
Some message
</tooltip-elem>
```
Note: target element must be a sibling element
=> Adds tooltip element <tooltip-elem>

cmd/openfish/entities/species.go, cmd/openfish/handlers/species.go, cmd/openfish/handlers/videostreams.go, cmd/openfish/main.go, cmd/openfish/services/capturesources_test.go, cmd/openfish/types/keypoint/keypoint.go
Misc. fixes to the species API
=> Species API fixes

app.yaml, docs/developer-docs/contributing.md, site/index.html, site/src/webcomponents/admin-menu.ts, site/src/webcomponents/site-nav.ts, site/src/webcomponents/stream-list.ts, site/src/webcomponents/user-provider.ts, site/watch.html
Also remove some stray whitespace characters
=> Use URLs without .html on the end for all pages

site/welcome.html
=> Update welcome page

site/src/app.css, site/src/webcomponents/image-carousel.ts, site/src/webcomponents/species-selection.ts, site/src/webcomponents/species-thumb.ts, site/src/webcomponents/watch-stream.ts
https://github.com/user-attachments/assets/7b80b73a-1859-445c-9452-f28b675ee79e
=> Add support for multiple images on species thumbnails

.github/workflows/deploy-documentation.yaml, .github/workflows/deploy-openfish.yaml, app.yaml, docs/developer-docs/api/operations/[operationId].paths.ts, docs/developer-docs/api/tags/[name].paths.ts, docs/developer-docs/contributing.md
Fix github actions, fix google app engine configuration, and update developer docs
=> Fix deployment issues

site/admin/capturesources.html, site/admin/species.html, site/admin/users.html, site/admin/videostreams.html, site/streams.html
=> Make footer stay at the bottom of the screen, even for short pages
